### ISSUE TITLE
3.15.0 "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by NorseGaud** [buildkite/agent#1094]
We just upgraded to 3.15.0 from 3.13.2 and notice the following happening, failing jobs for "agent lost":

```

2019-09-27 09:13:29 DEBUG  ↳ GET https://agent.buildkite.com/v3/ping proto=HTTP/2.0 status=200 Δ=27.245424ms
2019-09-27 09:13:29 DEBUG  GET https://agent.buildkite.com/v3/jobs/f1435cc1-436d-472b-9d89-c332a4e8cb09
2019-09-27 09:13:29 DEBUG  ↳ GET https://agent.buildkite.com/v3/jobs/f1435cc1-436d-472b-9d89-c332a4e8cb09 proto=HTTP/2.0 status=200 Δ=24.643231ms
2019-09-27 09:13:29 DEBUG  CICDM016-1 [HeaderTimesStreamer] Streamer has finished... 
2019-09-27 09:13:34 DEBUG  CICDM016-2 [HeaderTimesStreamer] Found header "+++ :evergreen_tree: Configuring Environment\r" 
2019-09-27 09:13:34 DEBUG  CICDM016-2 [HeaderTimesStreamer] Found header "+++ :leaves: Starting new MongoDB\r" 
2019-09-27 09:13:34 DEBUG  GET https://agent.buildkite.com/v3/ping
2019-09-27 09:13:34 DEBUG  ↳ GET https://agent.buildkite.com/v3/ping proto=HTTP/2.0 status=200 Δ=26.683683ms
2019-09-27 09:13:34 INFO   CICDM016-1 Assigned job 829066d6-3a94-41c9-a863-a764b02bc623. Accepting... 
2019-09-27 09:13:34 DEBUG  PUT https://agent.buildkite.com/v3/jobs/829066d6-3a94-41c9-a863-a764b02bc623/accept
2019-09-27 09:13:34 DEBUG  ↳ PUT https://agent.buildkite.com/v3/jobs/829066d6-3a94-41c9-a863-a764b02bc623/accept proto=HTTP/2.0 status=200 Δ=131.881632ms
2019-09-27 09:13:34 DEBUG  CICDM016-1 [JobRunner] Created env file: /var/folders/2w/gcjz3vsx7ms4362b757gtr0m0000gq/T/job-env-829066d6-3a94-41c9-a863-a764b02bc6
23244956696 
2019-09-27 09:13:34 DEBUG  CICDM016-1 [LineScanner] Starting to read lines 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1356aa6]

goroutine 86725 [running]:
github.com/buildkite/agent/process.(*Process).Done(0x0, 0xc0003fcfc0)
        /go/src/github.com/buildkite/agent/process/process.go:268 +0x26
github.com/buildkite/agent/agent.NewJobRunner.func3(0xc00016d040, 0xc00000e0d0, 0x2036840, 0xc000298200)
        /go/src/github.com/buildkite/agent/agent/job_runner.go:180 +0x36
created by github.com/buildkite/agent/agent.NewJobRunner
        /go/src/github.com/buildkite/agent/agent/job_runner.go:179 +0x92e

  _           _ _     _ _    _ _                                _
 | |         (_) |   | | |  (_) |                              | |
 | |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
 | '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
 | |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
 |_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
                                                __/ |
 http://buildkite.com/agent                    |___/

2019-09-27 09:13:34 NOTICE Starting buildkite-agent v3.15.0 with PID: 54968
2019-09-27 09:13:34 NOTICE The agent source code can be found here: https://github.com/buildkite/agent
2019-09-27 09:13:34 NOTICE For questions and support, email us at: hello@buildkite.com
2019-09-27 09:13:34 INFO   Configuration loaded path=/usr/local/etc/buildkite-agent/buildkite-agent.cfg
2019-09-27 09:13:34 DEBUG  Bootstrap command: /usr/local/bin/buildkite-agent bootstrap
2019-09-27 09:13:34 DEBUG  Build path: /Users/cicd/.buildkite-agent/builds
2019-09-27 09:13:34 DEBUG  Hooks directory: /usr/local/etc/buildkite-agent/hooks
2019-09-27 09:13:34 DEBUG  Plugins directory: /Users/cicd/.buildkite-agent/plugins
2019-09-27 09:13:34 INFO   Registering agent 1 of 2 with Buildkite...
```

- The resource usage looks ~ 50% for both CPU and memory at the time of the crash.
- We did not see this in the previous version we were using.

**Comment by NorseGaud** [comment]
Reverting to 3.13.2 with ```cd /usr/local/Homebrew/Library/Taps/buildkite/homebrew-buildkite && git checkout 30ffea13f5c124f680bff940c54058cd3aef7e29 && git reset --hard 30ffea13f5c124f680bff940c54058cd3aef7e29 && brew cleanup -s && HOMEBREW_NO_AUTO_UPDATE=1 brew install buildkite-agent```

**Comment by lox** [comment]
We’ll investigate and get a new version out shortly!

**Comment by keithpitt** [comment]
@lox this fixed?

**Comment by NorseGaud** [comment]
I see the release for 3.15.1. I'll close this and try the upgrade again.
