### ISSUE TITLE
Instance agent creation error with hibinit-agent

### ISSUE THREAD

**Issue by andrewhoplife** [buildkite/agent#1526]
I get this error with agent version numbers 5.6.1-5.7.0 using AMI ami-0db800b1d4e4c42ac. I am deploying this via cdk and cloudformation and  unless there are more errors I am not aware of the stack fails to complete setup after this error:

```
[[32m  OK  [0m] Stopped LVM2 metadata daemon.

[    7.327863] hibinit-agent[2794]: Traceback (most recent call last):

[    7.355289] hibinit-agent[2794]: File "/usr/bin/hibinit-agent", line 496, in <module>

[    7.357069] hibinit-agent[2794]: main()

[[1;31mFAILED[0m] Failed to start Initial hibernation setup job.

See 'systemctl status hibinit-agent.service' for details.

[    7.362801] hibinit-agent[2794]: File "/usr/bin/hibinit-agent", line 435, in main

[    7.365614] hibinit-agent[2794]: if not hibernation_enabled(config.state_dir):

[    7.365812] hibinit-agent[2794]: File "/usr/bin/hibinit-agent", line 390, in hibernation_enabled

[    7.367681] hibinit-agent[2794]: imds_token = get_imds_token()

[    7.367885] hibinit-agent[2794]: File "/usr/bin/hibinit-agent", line 365, in get_imds_token

[    7.368971] hibinit-agent[2794]: response = requests.put(token_url, headers=request_header)

[    7.369182] hibinit-agent[2794]: File "/usr/lib/python2.7/site-packages/requests/api.py", line 121, in put

[    7.371220] hibinit-agent[2794]: return request('put', url, data=data, **kwargs)

[    7.371428] hibinit-agent[2794]: File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request

[    7.373547] hibinit-agent[2794]: response = session.request(method=method, url=url, **kwargs)

[    7.373764] hibinit-agent[2794]: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request

[    7.375695] hibinit-agent[2794]: resp = self.send(prep, **send_kwargs)

[    7.375898] hibinit-agent[2794]: File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send

[    7.377122] hibinit-agent[2794]: r = adapter.send(request, **kwargs)

[    7.377337] hibinit-agent[2794]: File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 419, in send

[    7.379368] hibinit-agent[2794]: raise ConnectTimeout(e, request=request)

[    7.379564] hibinit-agent[2794]: requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/api/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7cef2835d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by keithduncan** [comment]
I’m not familiar with hibinit-agent, though it looks like this could be https://github.com/aws/amazon-ec2-hibinit-agent? Could you please provide a full steps to reproduce for this error and we can look into it, though you might be better served opening an issue in the hibinit-agent repo whose maintainers will have familiarity with the errors it generates 🙇

**Comment by keithduncan** [comment]
I’m going to close this as stale, please let us know if we can help further.
