### ISSUE TITLE
Beta agent crashes on macOS Sierra beta

### ISSUE THREAD

**Issue by mattdelves** [buildkite/agent#378]
When trying to run the buildkite agent 3.0beta-9 on macOS Sierra beta 6 I see a crash with the following stack trace.

```
buildkite-agent start

  _           _ _     _ _    _ _                                _
 | |         (_) |   | | |  (_) |                              | |
 | |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
 | '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
 | |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
 |_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
                                                __/ |
 http://buildkite.com/agent                    |___/

2016-09-03 15:27:12 NOTICE Starting buildkite-agent v3.0-beta.9 with PID: 53813
2016-09-03 15:27:12 NOTICE The agent source code can be found here: https://github.com/buildkite/agent
2016-09-03 15:27:12 NOTICE For questions and support, email us at: hello@buildkite.com
2016-09-03 15:27:12 INFO   Configuration loaded from: /usr/local/etc/buildkite-agent/buildkite-agent.cfg
2016-09-03 15:27:12 INFO   Registering agent with Buildkite...
2016-09-03 15:27:14 INFO   Successfully registered agent "MatthewsMacBook-1" with meta-data []
2016-09-03 15:27:14 INFO   Connecting to Buildkite...
2016-09-03 15:27:15 INFO   Agent successfully connected
2016-09-03 15:27:15 INFO   You can press Ctrl-C to stop the agent
2016-09-03 15:27:15 INFO   Waiting for work...
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x7641379e pc=0xd46f]

runtime stack:
runtime.throw(0x5182a0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x79
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x4d
runtime.unlock(0x6eee50)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x10f
runtime.startm(0x109a8000, 0x1)
	/usr/local/go/src/runtime/proc.go:1579 +0xcf
runtime.wakep()
	/usr/local/go/src/runtime/proc.go:1667 +0x4f
runtime.ready(0x10a69110, 0x4)
	/usr/local/go/src/runtime/proc.go:532 +0x102
runtime.goready.func1()
	/usr/local/go/src/runtime/proc.go:273 +0x21
runtime.systemstack(0x109a8a00)
	/usr/local/go/src/runtime/asm_386.s:313 +0x52
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 37 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_386.s:267 fp=0x10a79f0c sp=0x10a79f08
runtime.goready(0x10a69110, 0x4)
	/usr/local/go/src/runtime/proc.go:274 +0x30 fp=0x10a79f20 sp=0x10a79f0c
runtime.send(0x10d869c0, 0x10aaef00, 0x10a79fac, 0x10a79f68)
	/usr/local/go/src/runtime/chan.go:270 +0xa1 fp=0x10a79f34 sp=0x10a79f20
runtime.chansend(0x391ca0, 0x10d869c0, 0x10a79fac, 0x1, 0x1982f9, 0x0)
	/usr/local/go/src/runtime/chan.go:173 +0x1b9 fp=0x10a79f7c sp=0x10a79f34
runtime.chansend1(0x391ca0, 0x10d869c0, 0x10a79fac)
	/usr/local/go/src/runtime/chan.go:100 +0x38 fp=0x10a79f98 sp=0x10a79f7c
net/http.(*Transport).dialConn.func3(0x10e0e000, 0x10a80630, 0x10d869c0)
	/usr/local/go/src/net/http/transport.go:835 +0x69 fp=0x10a79fb8 sp=0x10a79f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1585 +0x1 fp=0x10a79fbc sp=0x10a79fb8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:836 +0x83f

goroutine 1 [select]:
github.com/buildkite/agent/agent.(*AgentWorker).Start(0x10d6a780, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/agent/agent_worker.go:89 +0x1cb
github.com/buildkite/agent/agent.(*AgentPool).Start(0x10a3ef40, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/agent/agent_pool.go:82 +0x759
github.com/buildkite/agent/clicommand.glob.func1(0x109f9920)
	/go/src/github.com/buildkite/agent/clicommand/agent_start.go:239 +0x420
github.com/buildkite/agent/vendor/github.com/codegangsta/cli.Command.Run(0x4887a0, 0x5, 0x0, 0x0, 0x4dbcc0, 0x18, 0x57c140, 0x1c2, 0x0, 0x0, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/codegangsta/cli/command.go:101 +0xba0
github.com/buildkite/agent/vendor/github.com/codegangsta/cli.(*App).Run(0x109e2e70, 0x1099e0f0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/codegangsta/cli/app.go:125 +0x8bf
main.main()
	/go/src/github.com/buildkite/agent/main.go:101 +0x3dd

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x118
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0x10d822a0)
	/usr/local/go/src/net/http/transport.go:1280 +0x330
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:861 +0xe3b

goroutine 33 [select, locked to thread]:
runtime.gopark(0x571818, 0x109b378c, 0x4884b0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x11e
runtime.selectgoImpl(0x109b378c, 0x0, 0xc)
	/usr/local/go/src/runtime/select.go:392 +0x9dc
runtime.selectgo(0x109b378c)
	/usr/local/go/src/runtime/select.go:215 +0xf
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x2bf
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1585 +0x1

goroutine 25 [IO wait]:
net.runtime_pollWait(0x30a16ea0, 0x72, 0x10d9c400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x4f
net.(*pollDesc).Wait(0x10d497b8, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x2f
net.(*pollDesc).WaitRead(0x10d497b8, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x2d
net.(*netFD).Read(0x10d49780, 0x10d9c400, 0x400, 0x400, 0x0, 0x30996030, 0x1099e098)
	/usr/local/go/src/net/fd_unix.go:250 +0x194
net.(*conn).Read(0x10d57708, 0x10d9c400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xb3
crypto/tls.(*block).readFromUntil(0x10d7b9e0, 0x3099a960, 0x10d57708, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0x9e
crypto/tls.(*Conn).readRecord(0x10c181c0, 0x571817, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x263
crypto/tls.(*Conn).Read(0x10c181c0, 0x10d85000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x12a
net/http.noteEOFReader.Read(0x30a1b558, 0x10c181c0, 0x10d822d4, 0x10d85000, 0x1000, 0x1000, 0x109d5dc4, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1690 +0x4f
net/http.(*noteEOFReader).Read(0x10daf7c0, 0x10d85000, 0x1000, 0x1000, 0x10a50340, 0x0, 0x0)
	<autogenerated>:284 +0xa8
bufio.(*Reader).fill(0x10db4840)
	/usr/local/go/src/bufio/bufio.go:97 +0x16c
bufio.(*Reader).Peek(0x10db4840, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xa7
net/http.(*persistConn).readLoop(0x10d822a0)
	/usr/local/go/src/net/http/transport.go:1076 +0x138
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:860 +0xe1b

goroutine 17 [IO wait]:
net.runtime_pollWait(0x30a16f90, 0x72, 0x10a96400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x4f
net.(*pollDesc).Wait(0x10a864f8, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x2f
net.(*pollDesc).WaitRead(0x10a864f8, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x2d
net.(*netFD).Read(0x10a864c0, 0x10a96400, 0x400, 0x400, 0x0, 0x30996030, 0x1099e098)
	/usr/local/go/src/net/fd_unix.go:250 +0x194
net.(*conn).Read(0x109b4dd0, 0x10a96400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xb3
crypto/tls.(*block).readFromUntil(0x10a43ae0, 0x3099a960, 0x109b4dd0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0x9e
crypto/tls.(*Conn).readRecord(0x109e6e00, 0x571817, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x263
crypto/tls.(*Conn).Read(0x109e6e00, 0x10c13000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x12a
net/http.noteEOFReader.Read(0x30a1b558, 0x109e6e00, 0x109e3684, 0x10c13000, 0x1000, 0x1000, 0x10d8cdc4, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1690 +0x4f
net/http.(*noteEOFReader).Read(0x10d68360, 0x10c13000, 0x1000, 0x1000, 0x109941a0, 0x0, 0x0)
	<autogenerated>:284 +0xa8
bufio.(*Reader).fill(0x10d6a5d0)
	/usr/local/go/src/bufio/bufio.go:97 +0x16c
bufio.(*Reader).Peek(0x10d6a5d0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xa7
net/http.(*persistConn).readLoop(0x109e3650)
	/usr/local/go/src/net/http/transport.go:1076 +0x138
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:860 +0xe1b

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0x109e3650)
	/usr/local/go/src/net/http/transport.go:1280 +0x330
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:861 +0xe3b

goroutine 34 [chan receive]:
github.com/buildkite/agent/signalwatcher.Watch.func1(0x10d86100, 0x10dd60c0)
	/go/src/github.com/buildkite/agent/signalwatcher/watcher_unix.go:20 +0x39
created by github.com/buildkite/agent/signalwatcher.Watch
	/go/src/github.com/buildkite/agent/signalwatcher/watcher_unix.go:33 +0x25d

goroutine 50 [runnable]:
net/http.(*Transport).dialConn(0x10bf1780, 0x0, 0x10aaed80, 0x5, 0x10aace40, 0x17, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:837 +0x871
net/http.(*Transport).getConn.func4(0x10bf1780, 0x0, 0x10aaed80, 0x5, 0x10aace40, 0x17, 0x10ab6480)
	/usr/local/go/src/net/http/transport.go:709 +0x47
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:711 +0x1fb

goroutine 35 [sleep]:
time.Sleep(0xa817c800, 0x4)
	/usr/local/go/src/runtime/time.go:59 +0xda
github.com/buildkite/agent/agent.(*AgentWorker).Start.func1(0x10d6a780, 0xa817c800, 0x4)
	/go/src/github.com/buildkite/agent/agent/agent_worker.go:76 +0x14e
created by github.com/buildkite/agent/agent.(*AgentWorker).Start
	/go/src/github.com/buildkite/agent/agent/agent_worker.go:78 +0x91

goroutine 27 [chan receive]:
net/http.(*Transport).getConn.func2.1(0x10ab6480, 0x10bf1780, 0x571604)
	/usr/local/go/src/net/http/transport.go:698 +0x39
created by net/http.(*Transport).getConn.func2
	/usr/local/go/src/net/http/transport.go:702 +0x5a
```

**Comment by toolmantim** [comment]
The latest experimental builds include this now: `http://download.buildkite.com/agent/experimental/latest/buildkite-agent-darwin-amd64`
