### ISSUE TITLE
Go panic during cancellation operation

### ISSUE THREAD

**Issue by avsm** [buildkite/agent#777]
which trying to cancel a job (https://buildkite.com/ocaml/opam-bulk/builds/566#de56f698-540e-4876-834c-64e73b5fb80f) running agent v3.1.1, I ran across this go panic in the agent... 

```
2018-05-25 08:44:56 INFO   Reading pipeline config from "tobuild.yml"
--
  | 2018-05-25 08:45:47 WARN   POST https://agent.buildkite.com/v3/jobs/de56f698-540e-4876-834c-64e73b5fb80f/pipelines: 102 (Attempt 1/5 Retrying in 1s)
  | 2018-05-25 08:46:48 WARN   Post https://agent.buildkite.com/v3/jobs/de56f698-540e-4876-834c-64e73b5fb80f/pipelines: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Attempt 2/5 Retrying in 1s)
  | panic: interface conversion: error is *url.Error, not *api.ErrorResponse
  |  
  | goroutine 1 [running]:
  | github.com/buildkite/agent/clicommand.glob..func10.1(0xc4202e9720, 0xdcb600, 0xc420553c40)
  | /go/src/github.com/buildkite/agent/clicommand/pipeline_upload.go:193 +0x290
  | github.com/buildkite/agent/retry.Do(0xc420570c00, 0xc420310100, 0xc42002606d, 0x32)
  | /go/src/github.com/buildkite/agent/retry/retry.go:80 +0x1cf
  | github.com/buildkite/agent/clicommand.glob..func10(0xc420180b00)
  | /go/src/github.com/buildkite/agent/clicommand/pipeline_upload.go:189 +0x609
  | github.com/buildkite/agent/vendor/github.com/urfave/cli.HandleAction(0xb668a0, 0xd5b540, 0xc420180b00, 0xc4201c7000, 0x0)
  | /go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:504 +0x7c
  | github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0xd26da4, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd523d9, 0x67, 0x0, ...)
  | /go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:210 +0xa50
  | github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc42029c380, 0xc420180840, 0x0, 0x0)
  | /go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:383 +0xa6b
  | github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.startApp(0xd28a7e, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd4e2c6, 0x3b, 0x0, ...)
  | /go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:298 +0x8d9
  | github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0xd28a7e, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd4e2c6, 0x3b, 0x0, ...)
  | /go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:98 +0x129d
  | github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).Run(0xc42029c1c0, 0xc42013c000, 0x4, 0x4, 0x0, 0x0)
  | /go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:259 +0x6e8
  | main.main()
  | /go/src/github.com/buildkite/agent/main.go:102 +0x4ef
  | 🚨 Error: The command exited with status 2

```

**Comment by avsm** [comment]
I hope I haven't messed something up, as now all the agents are failing to connect with a HTTP 502 error.

```
2018-05-25 09:28:10 WARN   POST https://agent.buildkite.com/v3/register: 502 (Attempt 1/30 Retrying in 10s)
```

**Comment by lox** [comment]
Thanks @avsm, we'll get this fixed.
